all:
	gcc -shared -o RR_API_cpp.dll RR_API.cpp -lws2_32 -Wl,--output-def,RR_API_cpp.def,--out-implib,RR_API_cpp.a

#"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat"
#lib.exe /machine:i386 /def:RR_API_cpp.def
